# Generated by Django 5.2.1 on 2025-08-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('data_partida', models.DateTimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assentos_totais', models.IntegerField()),
                ('assentos_reservados', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assento_numero', models.IntegerField()),
                ('telefone', models.CharField(max_length=20)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='viagens.passageiro')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='viagens.viagem')),
            ],
        ),
    ]
